<a href="https://colab.research.google.com/github/divs1111/Python-study/blob/main/1st.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!unzip python-novice-inflammation-data.zip

Archive:  python-novice-inflammation-data.zip
   creating: data/
  inflating: data/inflammation-01.csv  
  inflating: data/inflammation-02.csv  
  inflating: data/inflammation-03.csv  
  inflating: data/inflammation-04.csv  
  inflating: data/inflammation-05.csv  
  inflating: data/inflammation-06.csv  
  inflating: data/inflammation-07.csv  
  inflating: data/inflammation-08.csv  
  inflating: data/inflammation-09.csv  
  inflating: data/inflammation-10.csv  
  inflating: data/inflammation-11.csv  
  inflating: data/inflammation-12.csv  
 extracting: data/small-01.csv       
 extracting: data/small-02.csv       
 extracting: data/small-03.csv       


In [2]:
planet = 'Earth'

In [3]:
type(planet)

str

In [5]:
import numpy

In [14]:
numpy.loadtxt(fname='./data/inflammation-01.csv', delimiter =',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

# New Section

In [21]:
data = numpy.loadtxt(fname = './data/inflammation-01.csv', delimiter = ',')

In [22]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [23]:
type(data)

numpy.ndarray

In [25]:
print(data.dtype)

float64


In [26]:
print(data.shape)

(60, 40)


In [27]:
print('first value in data',data[0,0])

first value in data 0.0


In [28]:
print('last value in data',data[59,39])

last value in data 0.0


In [29]:
print(data[0:10, 0:20])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7.]
 [ 0.  1.  1.  3.  3.  1.  3.  5.  2.  4.  4.  7.  6.  5.  3. 10.  8. 10.
   6. 17.]
 [ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.  7.  6.  6.  9.  9. 15.  4. 16.
  18. 12.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.  6.  5. 11.  9.  4. 13.  5. 12.
  10.  6.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.  7.  8.  8.  5. 10.  9. 15. 11.
  18. 19.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.  2.  4. 11. 12. 10. 11.  9. 10.
  17. 11.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.  6.  8. 12.  5. 13.  6. 13.  8.
  16.  8.]]


In [30]:
print(numpy.mean(data))

6.14875


In [34]:
x = numpy.mean(data)
print(x)

6.14875


In [36]:
import time
print(time.ctime())

Sat Sep 11 05:48:24 2021


In [38]:
print('maximum inflammation', numpy.max(data))
print('minimum inflammation', numpy.min(data))
print('standard deviation', numpy.std(data))

maximum inflammation 20.0
minimum inflammation 0.0
standard deviation 4.613833197118566


In [40]:
print('maximum inflammation of patient 0 is', numpy.max(data[0,:]))

maximum inflammation of patient 0 is 18.0


In [42]:
print('minimum inflammation of patient 2 is', numpy.min(data[2:]))

minimum inflammation of patient 2 is 0.0


In [45]:
print(numpy.max(data, axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [46]:
print(numpy.max(data, axis=0).shape)

(40,)


In [48]:
element = 'oxygen';
print(element[1:-1])

xyge


In [50]:
print(data[3:3,4:4])
print(data[3:3,:])

[]
[]


In [92]:
A = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print('A =')
print(A)
B = A[:, 0:3:2]
print('B =')
print(B)

A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B =
[[1 3]
 [4 6]
 [7 9]]


In [99]:
D = numpy.hstack((A[:,:1],A[:,-1:]))
print(D)

[[1 3]
 [4 6]
 [7 9]]
